# Usa una imagen de Python 3.11
FROM python:3.11

# Instala las dependencias necesarias para OpenCV y OpenGL
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la carpeta padre al directorio /app
COPY . /app

# Crea un volumen que mapea la ruta local /home/admincamaras/CamarasBiblioteca/Compartida
# a /app/Compartida en el contenedor
VOLUME /home/admincamaras/CamarasBiblioteca/Compartida:/app/Compartida

# Limita la CPU a 0.5 (50% de una CPU)
# Si tienes más de una CPU disponible en tu sistema, esto limitará el contenedor a usar la mitad de un núcleo.
# Si tienes 4 CPUs, 0.5 significa 50% de un núcleo.
ENV CPU_LIMIT 0.5

# Instala los requisitos desde el archivo requirements.txt
RUN pip install opencv-contrib-python
RUN pip install pika
RUN pip install ping3
RUN pip install pyTelegramBotAPI
RUN pip install python-dotenv
RUN pip install numpy

# Nombre del contenedor
LABEL name="Camara_ANT"

# Indica que el contenedor escucha en el puerto RTSP
EXPOSE 554

# Comando de inicio
CMD ["python", "Camara_ANT.py"]
