# Usa una imagen de Python 3.11
FROM python:3.8

# Instala las dependencias necesarias para OpenCV y OpenGL
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6
    

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la carpeta padre al directorio /app
COPY . /app

# Crea un volumen que mapea la ruta local /home/admincamaras/CamarasBiblioteca/Compartida
# a /app/Compartida en el contenedor
VOLUME /home/admincamaras/CamarasBiblioteca/Compartida:/app/Compartida

# Limita la CPU a 0.15 (15% de una CPU)
# Si tienes más de una CPU disponible en tu sistema, esto limitará el contenedor a usar la mitad de un núcleo.
# Si tienes 4 CPUs, 0.5 significa 15% de un núcleo.
ENV CPU_LIMIT 1.5

# Instala los requisitos desde el archivo requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install python-dotenv
RUN pip install opencv-python
RUN pip install pika
RUN pip install torch
RUN pip install numpy
RUN pip install pandas
RUN pip install mysql-connector-python

# Nombre del contenedor
LABEL name="detector"

# Comando de inicio
CMD ["python", "Detector.py"]