# Usa una imagen de Python 3.11
FROM python:3.11

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos de la carpeta padre al directorio /app
COPY . /app

# Crea un volumen que mapea la ruta local /home/admincamaras/CamarasBiblioteca/Compartida
# a /app/Compartida en el contenedor
VOLUME /home/admincamaras/CamarasBiblioteca/Compartida:/app/Compartida

# Limita la CPU a 0.2 (20% de una CPU)
ENV CPU_LIMIT 0.2

# Instala los requisitos desde el archivo requirements.txt
RUN pip install python-dotenv
RUN pip install pandas

# Nombre del contenedor
LABEL name="informes"

# Comando de inicio
CMD ["python", "informes.py"]